name: SIL Blinky Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 5 * * 5'

jobs:
  unit-tests:
    name: Run Build Tests (py${{ matrix.python-version }}/${{ matrix.os }})
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        python-version:
          - '3.11'
        os:
          - linux
        include:
          - os: linux
            os-version: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Install FreeRTOS dependencies into environment
        shell: bash -l {0}
        run: |
          sudo apt-get install -y build-essential gcc gdb make libpcap-dev

      - name: Activate spansil environment (${{ matrix.python-version }})
        uses: conda-incubator/setup-miniconda@main
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: spansil

      - name: Install SpanSIL dependencies into environment
        shell: bash -l {0}
        run: |
          conda init
          conda activate spansil
          conda install -c conda-forge doxygen pytest
          conda list

      - name: Grab GitSubmodules
        shell: bash -l {0}
        run: |
          git submodule update --init --recursive

      - name: Run Blink Test
        shell: bash -l {0}
        run: |
          conda activate spansil
          cd FreeRTOS/SIL/Posix_GCC
          pytest
          make clean
